GradeRegZTP/Models/Grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GradeRegZTP.Models
{
    public partial class Grade
    {
        [Key]
        public int Id { get; set; }
        public int SubjectId { get; set; }

        public decimal Value { get; set; }
        public decimal Weight { get; set; }
        public string Note { get; set; }       
        public DateTime? Date { get; set; }
        public string Owner { get; set; }

        [ForeignKey("SubjectId")]
        public virtual Subject Subject { get; set; }
    }

    public partial class Grade
    {
        
    }
}

GradeRegZTP/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradeRegZTP.Models;
using GradeRegZTP.Services;
using GradeRegZTP.ViewModel;
using Microsoft.AspNet.Identity;

namespace GradeRegZTP.Controllers
{
    [Authorize]
    public class GradesController : Controller
    {
        private IDbContext db;
        private IGradeService gradeService;

        public GradesController(IDbContext _db)
        {
            db = _db;
            gradeService = new GradeProxy(new GradeService(_db));
        }


        // GET: Grades
        public ActionResult Index()
        {
            var userID = User.Identity.GetUserId();
            if (User.IsInRole("Admin"))
            {
                var grades = gradeService.GetAllGrades();
                return View(grades.ToList());
            }
            else if (User.IsInRole("Teacher"))
            {
                var subjectStudentsGroup = db.SubjectStudentGroupTeacher.Where(x => x.TeacherID == userID).Select(x => new TeacherGradesViewModel()
                {
                    Subject = x.Subject,
                    StudentsGroup = x.StudentsGroup
                }).Distinct().ToList();




                return View("~\\Views\\Grades\\IndexTeacher.cshtml", subjectStudentsGroup);
            }
            else if (User.IsInRole("Student"))
            {
                var myStudentGrupuID = db.MyUsers.Where(x => x.Owner == userID).Select(x => x.StudentsGroupId).FirstOrDefault();

                var grades = Helper.ToIEnumerable<Grade>(gradeService.GradesForStudent(userID));
                var subjects = db.SubjectStudentGroupTeacher.Where(x => x.StudentsGroupId == myStudentGrupuID).Select(x => x.Subject).ToList();


                StudentGradesViewModel studentViewModel = new StudentGradesViewModel()
                {
                    Grades = grades,
                    Subjects = subjects
                };

                return View("~\\Views\\Grades\\IndexStudent.cshtml", studentViewModel);
            }
            return View();
        }



        // GET: Grades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = db.Grades.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // GET: Grades/Create
        public ActionResult Create()
        {
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name");
            return View();
        }

        // POST: Grades/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SubjectId,Value,Weight,Note,Date,Owner")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                gradeService.AddGrade(grade);
                return RedirectToAction("Index");
            }

            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", grade.SubjectId);
            return View(grade);
        }

        // GET: Grades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = gradeService.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", grade.SubjectId);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SubjectId,Value,Weight,Note,Date,Owner")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                gradeService.UpdateGrade(grade);
                return RedirectToAction("Index");
            }
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", grade.SubjectId);
            return View(grade);
        }

        // GET: Grades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grade grade = gradeService.Find(id);
            if (grade == null)
            {
                return HttpNotFound();
            }
            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            gradeService.DeleteGrade(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


}

GradeRegZTP/Controllers/StudentsGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradeRegZTP.Models;
using GradeRegZTP.ViewModel;

namespace GradeRegZTP.Controllers
{
    [Authorize]
    public class StudentsGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: StudentsGroups
        public ActionResult Index()
        {
            return View(db.StudentsGroups.ToList());
        }

        public ActionResult AddGrade(int? studentGroupId, int? subjectId)
        {
            if (User.IsInRole("Teacher"))
            {
                var studentsGroup = db.StudentsGroups.FirstOrDefault(x => x.Id == studentGroupId);
                var subjectName = db.Subjects.FirstOrDefault(x => x.Id == subjectId).Name;

                var myUsers = db.MyUsers.Where(x => x.StudentsGroupId == studentGroupId).Select(x => new StudentsGroupAddGradeViewModel()
                {
                    MyUserId = x.Owner,
                    MyUser = x,
                    SubjectName = subjectName,
                    StudentGroupName = studentsGroup.Level + studentsGroup.Name,
                    SubjectId = (int)subjectId,
                    StudentsGroupId = (int)studentGroupId
                }).ToList();

                StudentsGroupAddGradeViewModelList model = new StudentsGroupAddGradeViewModelList();
                model.StudentsGroupAddGradeViewModels = myUsers;


                return View("~\\Views\\StudentsGroups\\AddGradeTeacher.cshtml", model);
            }
            return HttpNotFound();
        }
        [HttpPost]

        [ValidateAntiForgeryToken]
        public ActionResult AddGrade([Bind(Include = "StudentsGroupAddGradeViewModels")]  StudentsGroupAddGradeViewModelList model)
        {
            foreach (var studentsGroupAddGradeViewModels in model.StudentsGroupAddGradeViewModels)
            {
                if (studentsGroupAddGradeViewModels.Note != null)
                {
                    var grade = new Grade()
                    {
                        Value = studentsGroupAddGradeViewModels.Grade.Value,
                        Owner = studentsGroupAddGradeViewModels.MyUserId,
                        Note = studentsGroupAddGradeViewModels.Note,
                        Date = DateTime.Now,
                        SubjectId = studentsGroupAddGradeViewModels.SubjectId,
                        Weight = studentsGroupAddGradeViewModels.Weight.Value
                    };
                    db.Grades.Add(grade);
                }
            }
            db.SaveChanges();
            if (!model.StudentsGroupAddGradeViewModels.Any())
            {
                return View("~\\Views\\Grades\\index.cshtml");
            }

            return RedirectToAction("Index", "Grades", new { id = 1 });
        }
        public ActionResult Details(int? studentGroupId, int? subjectId)
        {
            if (studentGroupId == null || studentGroupId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.IsInRole("Teacher"))
            {
                var studentsGroup = db.StudentsGroups.FirstOrDefault(x => x.Id == studentGroupId);
                var subjectName = db.Subjects.FirstOrDefault(x => x.Id == subjectId).Name;

                var myUsers = db.MyUsers.Where(x => x.StudentsGroupId == studentGroupId).Select(x => new StudentGroupViewModel()
                {
                    MyUser = x,
                    SubjectName = subjectName,
                    StudentGroupName = studentsGroup.Level + studentsGroup.Name,
                    StudentGroupId = (int)studentGroupId,
                    SubjectId = (int)subjectId
                }).ToList();


                foreach (var myUser in myUsers)
                {
                    myUser.Grades = db.Grades.Where(x => x.Owner == myUser.MyUser.Owner && x.SubjectId == subjectId).ToList();
                }

                return View("~\\Views\\StudentsGroups\\DetailsTeacher.cshtml", myUsers);
            }

            StudentsGroup StudentsGroup = db.StudentsGroups.Find(studentGroupId);
            if (StudentsGroup == null)
            {
                return HttpNotFound();
            }
            return View(StudentsGroup);
        }
        // GET: StudentsGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentsGroups/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Level")] StudentsGroup StudentsGroup)
        {
            if (ModelState.IsValid)
            {
                db.StudentsGroups.Add(StudentsGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(StudentsGroup);
        }

        // GET: StudentsGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentsGroup StudentsGroup = db.StudentsGroups.Find(id);
            if (StudentsGroup == null)
            {
                return HttpNotFound();
            }
            return View(StudentsGroup);
        }

        // POST: StudentsGroups/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Level")] StudentsGroup StudentsGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(StudentsGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(StudentsGroup);
        }

        // GET: StudentsGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentsGroup StudentsGroup = db.StudentsGroups.Find(id);
            if (StudentsGroup == null)
            {
                return HttpNotFound();
            }
            return View(StudentsGroup);
        }

        // POST: StudentsGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentsGroup StudentsGroup = db.StudentsGroups.Find(id);
            db.StudentsGroups.Remove(StudentsGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GradeRegZTP/Views/Grades/Create.cshtml
@model GradeRegZTP.Models.Grade

<h2>Dodaj oceny</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradeRegZTP/Views/Grades/Delete.cshtml
@model GradeRegZTP.Models.Grade

<h2>Usuń ocenę</h2>

<h3>Czy na pewno chcesz to usunąć?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróc", "Index")
        </div>
    }
</div>

GradeRegZTP/Views/Grades/Details.cshtml
@model GradeRegZTP.Models.Grade

<h2>Szczegóły</h2>

<div>
    <h4>Ocena</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>


<p>
    @if (User.IsInRole("Teacher") || User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id })
        <span> |</span>
        @Html.ActionLink("Usuń", "Delete", new { id = Model.Id })
        <span> |</span>
    }

    @Html.ActionLink("Wróć", "Index")
</p>

GradeRegZTP/Views/Grades/Edit.cshtml
@model GradeRegZTP.Models.Grade

<h2>Edytuj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ocena</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Date )
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
             <div class="col-md-10">
                @Html.HiddenFor(model => model.Owner )
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradeRegZTP/Views/Grades/Index.cshtml
@model IEnumerable<GradeRegZTP.Models.Grade>

<h2>Oceny</h2>

<p>
    @Html.ActionLink("Dodaj nowy", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owner)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

GradeRegZTP/Views/Grades/IndexStudent.cshtml
@model  GradeRegZTP.ViewModel.StudentGradesViewModel

<h2>Oceny</h2>

<table class="table">
    <tr>
        <th width="10%">
            Przedmiot
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grades.FirstOrDefault().Value)
        </th>
    </tr>

    @foreach (var item in Model.Subjects.Distinct())
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var grade in Model.Grades.Where(x => x.SubjectId == item.Id))
                {
                    @Html.ActionLink(@Math.Round(grade.Value, 1).ToString() + " ", "Details", new { id = grade.Id })

                }
            </td>
        </tr>
    }
</table>

GradeRegZTP/Views/Grades/IndexTeacher.cshtml
@model IEnumerable<GradeRegZTP.ViewModel.TeacherGradesViewModel>



<h2>Grupy zajęciowe</h2>

<table class="table">
    <tr>
        <th width="10%">
            Przedmiot
        </th>
        <th>
            Klasa
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Subject.Name, "Details", "StudentsGroups", routeValues: new { studentGroupId = item.StudentsGroup.Id, subjectId = item.Subject.Id }, htmlAttributes: null)

            </td>
            <td>
                @item.StudentsGroup.Level@item.StudentsGroup.Name
            </td>
        </tr>
    }

</table>