GradeRegZTP/Models/HourOfDay.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GradeRegZTP.Models
{
    public class HourOfDay
    {
        [Key]
        public int Id { get; set; }

        public int HourId { get; set; }
        public int SubjectId { get; set; }
        public int StudentsGroupId { get; set; }
        public int DayOfWeekId { get; set; }

        [ForeignKey("SubjectId")]
        public virtual Subject Subject { get; set; }
        [ForeignKey("StudentsGroupId")]
        public virtual StudentsGroup StudentsGroup { get; set; }
        [ForeignKey("DayOfWeekId")]
        public virtual DayOfWeek DayOfWeek { get; set; }
        [ForeignKey("HourId")]
        public virtual Hour Hour { get; set; }
    }
}

GradeRegZTP/Controllers/HourOfDaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GradeRegZTP.Builder;
using GradeRegZTP.Models;
using Microsoft.AspNet.Identity;

namespace GradeRegZTP.Controllers
{
    [Authorize]
    public class HourOfDaysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private PDFTimetableBuilder PDFBuilder = new PDFTimetableBuilder();

        // GET: HourOfDays1
        public ActionResult Index()
        {
            var userID = User.Identity.GetUserId();
            if (User.IsInRole("Admin"))
            {
                var hourOfDays = db.HourOfDays.Include(h => h.DayOfWeek).Include(h => h.Hour).Include(h => h.StudentsGroup).Include(h => h.Subject);
                return View(hourOfDays.ToList());
            }
            else if (User.IsInRole("Teacher"))
            {
                var hourOfDays = db.SubjectStudentGroupTeacher
                    .Join(db.HourOfDays,
                    SSGT => new { StudentsGroupId = SSGT.StudentsGroupId, SubjectId = SSGT.SubjectId },
                    HoD => new { StudentsGroupId = HoD.StudentsGroupId, SubjectId = HoD.SubjectId },
                    (SSGT, HoD) => new { SSGT, HoD })
                    .Where(x => x.SSGT.TeacherID == userID)
                    .Select(x => x.HoD)
                    .Distinct()
                    .ToList();
                return View("~\\Views\\HourOfDays\\IndexTeacher.cshtml", hourOfDays);

            }
            else
            {
                var hourOfDays = db.HourOfDays.Include(h => h.DayOfWeek).Include(h => h.Hour).Include(h => h.StudentsGroup).Include(h => h.Subject).Where(x => x.StudentsGroupId == db.MyUsers.FirstOrDefault(xd => xd.Owner == userID).StudentsGroupId).ToList();
                return View("~\\Views\\HourOfDays\\IndexStudent.cshtml", hourOfDays);
            }
        }

        // GET: HourOfDays1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourOfDay hourOfDay = db.HourOfDays.Find(id);
            if (hourOfDay == null)
            {
                return HttpNotFound();
            }
            return View(hourOfDay);
        }

        // GET: HourOfDays1/Create
        public ActionResult Create()
        {
            ViewBag.DayOfWeekId = new SelectList(db.DayOfWeek, "Id", "Name");
            ViewBag.HourId = new SelectList(db.Hours, "Id", "HourString");
            ViewBag.StudentsGroupId = new SelectList(db.StudentsGroups.Select(x => new { Id = x.Id, Name = x.Level + x.Name }), "Id", "Name");
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name");
            return View();
        }

        // POST: HourOfDays1/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HourId,SubjectId,StudentsGroupId,DayOfWeekId")] HourOfDay hourOfDay)
        {
            if (ModelState.IsValid)
            {
                db.HourOfDays.Add(hourOfDay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DayOfWeekId = new SelectList(db.DayOfWeek, "Id", "Name", hourOfDay.DayOfWeekId);
            ViewBag.HourId = new SelectList(db.Hours, "Id", "HourString", hourOfDay.HourId);
            ViewBag.StudentsGroupId = new SelectList(db.StudentsGroups, "Id", "Name", hourOfDay.StudentsGroupId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", hourOfDay.SubjectId);
            return View(hourOfDay);
        }

        // GET: HourOfDays1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourOfDay hourOfDay = db.HourOfDays.Find(id);
            if (hourOfDay == null)
            {
                return HttpNotFound();
            }
            ViewBag.DayOfWeekId = new SelectList(db.DayOfWeek, "Id", "Name", hourOfDay.DayOfWeekId);
            ViewBag.HourId = new SelectList(db.Hours, "Id", "HourString", hourOfDay.HourId);
            ViewBag.StudentsGroupId = new SelectList(db.StudentsGroups, "Id", "Name", hourOfDay.StudentsGroupId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", hourOfDay.SubjectId);
            return View(hourOfDay);
        }

        // POST: HourOfDays1/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HourId,SubjectId,StudentsGroupId,DayOfWeekId")] HourOfDay hourOfDay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hourOfDay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DayOfWeekId = new SelectList(db.DayOfWeek, "Id", "Name", hourOfDay.DayOfWeekId);
            ViewBag.HourId = new SelectList(db.Hours, "Id", "HourString", hourOfDay.HourId);
            ViewBag.StudentsGroupId = new SelectList(db.StudentsGroups, "Id", "Name", hourOfDay.StudentsGroupId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", hourOfDay.SubjectId);
            return View(hourOfDay);
        }

        // GET: HourOfDays1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourOfDay hourOfDay = db.HourOfDays.Find(id);
            if (hourOfDay == null)
            {
                return HttpNotFound();
            }
            return View(hourOfDay);
        }

        // POST: HourOfDays1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HourOfDay hourOfDay = db.HourOfDays.Find(id);
            db.HourOfDays.Remove(hourOfDay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult PDFGenerator()
        {
            var userID = User.Identity.GetUserId();
            List<HourOfDay> lessons;
            if (User.IsInRole("Teacher"))
            {
                lessons = db.SubjectStudentGroupTeacher
                    .Join(db.HourOfDays,
                    SSGT => new { StudentsGroupId = SSGT.StudentsGroupId, SubjectId = SSGT.SubjectId },
                    HoD => new { StudentsGroupId = HoD.StudentsGroupId, SubjectId = HoD.SubjectId },
                    (SSGT, HoD) => new { SSGT, HoD })
                    .Where(x => x.SSGT.TeacherID == userID)
                    .Select(x => x.HoD)
                    .Distinct()
                    .ToList();
            }
            else
            {
                lessons = db.HourOfDays.Include(h => h.DayOfWeek)
                    .Include(h => h.Hour).Include(h => h.StudentsGroup)
                    .Include(h => h.Subject)
                    .Where(x => x.StudentsGroupId == db.MyUsers.FirstOrDefault(xd => xd.Owner == userID).StudentsGroupId).ToList();
            }
            CreateTimetable(PDFBuilder, lessons);
            
            return PDFBuilder.GeneratePDF(); 
        }

        private void CreateTimetable(ITimetableBuilder builder, List<HourOfDay> lessons)
        {
            builder.AddHeader();
            builder.AddColumn("Godzina");
            builder.AddColumn("Poniedziałek");
            builder.AddColumn("Wtorek");
            builder.AddColumn("Środa");
            builder.AddColumn("Czwartek");
            builder.AddColumn("Piątek");
            builder.AddColumn("Sobota");
            builder.AddColumn("Niedziela");

            for (int j = 8; j <= 18; j++)
            {
                var godzina = j + ":15";
                builder.AddRow();
                builder.AddColumn(godzina);
                for (int i = 1; i < 8; i++)
                {
                    var dzienTygodnia = i;
                    var zajecie = lessons.Where(x => x.Hour.HourString.Equals(godzina) && x.DayOfWeekId == dzienTygodnia).FirstOrDefault();
                    if (zajecie != null)
                        builder.AddColumn(zajecie.Subject.Name);
                    else
                        builder.AddColumn("");
                }
            }
        }
    }
}

GradeRegZTP/Views/HourOfDays/Create.cshtml
@model GradeRegZTP.Models.HourOfDay

@{
    ViewBag.Title = "Create";
}

<h2>Utwórz</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zajęcia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HourId, "HourId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HourId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HourId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentsGroupId, "StudentsGroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentsGroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentsGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeekId, "DayOfWeekId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayOfWeekId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayOfWeekId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradeRegZTP/Views/HourOfDays/Delete.cshtml
@model GradeRegZTP.Models.HourOfDay

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz to usunąć?</h3>
<div>
    <h4>Zajęcia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DayOfWeek.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayOfWeek.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hour.HourString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hour.HourString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentsGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentsGroup.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć", "Index")
        </div>
    }
</div>

GradeRegZTP/Views/HourOfDays/Details.cshtml
@model GradeRegZTP.Models.HourOfDay

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div>
    <h4>Zajęcia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DayOfWeek.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayOfWeek.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hour.HourString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hour.HourString)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentsGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentsGroup.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Wróć", "Index")
</p>

GradeRegZTP/Views/HourOfDays/Edit.cshtml
@model GradeRegZTP.Models.HourOfDay

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zajęcia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HourId, "HourId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HourId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HourId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentsGroupId, "StudentsGroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentsGroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentsGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeekId, "DayOfWeekId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DayOfWeekId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayOfWeekId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GradeRegZTP/Views/HourOfDays/Index.cshtml
@model IEnumerable<GradeRegZTP.Models.HourOfDay>

<h2>Rozkład zajęć</h2>

<p>
    @Html.ActionLink("Dodaj nowy", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DayOfWeek.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hour.HourString)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentsGroup.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DayOfWeek.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hour.HourString)
        </td>
        <td>
            @item.StudentsGroup.Level@item.StudentsGroup.Name
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject.Name)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

GradeRegZTP/Views/HourOfDays/IndexStudent.cshtml
@model IEnumerable<GradeRegZTP.Models.HourOfDay>

 
<style>
    .info {
        border: 1px #5b5757 solid;
    }
</style>
<h2>Rozkład zajęć</h2>
<table class="table">
    <tr>
        <th>
            Godzina
        </th>
        <th>
            Poniedziałek
        </th>
        <th>
            Wtorek
        </th>
        <th>
            Środa
        </th>
        <th>
            Czwartek
        </th>
        <th>Piątek</th>
        <th>Sobota</th>
        <th>Niedziela</th>
    </tr>

    @for (int j = 8; j <= 18; j++)
    {
        var godzina = j + ":15";
        <tr>
            <td>
                @godzina
            </td>
            @for (int i = 1; i < 8; i++)
            {

                var dzienTygodnia = i;
                var zajecie = Model.Where(x => x.Hour.HourString.Equals(godzina) && x.DayOfWeekId == dzienTygodnia).FirstOrDefault();
                <td width="14%" class="info">
                    @if (zajecie != null)
                    {
                        <p> @zajecie.Subject.Name</p>
                        // TODO dodac nauczycieli
                    }
                </td>
            }
        </tr>
    }

</table>
@Html.ActionLink("Pobierz PDF", "PDFGenerator", "HourOfDays", new { @class = "btn btn-danger" })

GradeRegZTP/Views/HourOfDays/IndexTeacher.cshtml
@model IEnumerable<GradeRegZTP.Models.HourOfDay>
 
 
<style>
    .info {
        border: 1px #5b5757 solid;
    }
</style>
<h2>Rozkład zajęć</h2>
<table class="table">
    <tr>
        <th>
            Godzina
        </th>
        <th>
            Poniedziałek
        </th>
        <th>
            Wtorek
        </th>
        <th>
            Środa
        </th>
        <th>
            Czwartek
        </th>
        <th>Piątek</th>
        <th>Sobota</th>
        <th>Niedziela</th>
    </tr>

    @for (int j = 8; j <= 18; j++)
    {
        var godzina = j + ":15";
        <tr>
            <td>
                @godzina
            </td>
            @for (int i = 1; i < 8; i++)
            {

                var dzienTygodnia = i;
                var zajecie = Model.Where(x => x.Hour.HourString.Equals(godzina) && x.DayOfWeekId == dzienTygodnia).FirstOrDefault();
                <td width="14%" class="info">
                    @if (zajecie != null)
                    {
                        <p> @zajecie.Subject.Name</p>
                        // TODO dodac nauczycieli
                    }
                </td>
            }
        </tr>
    }
</table>
@Html.ActionLink("Pobierz PDF", "PDFGenerator", "HourOfDays", new { @class = "btn btn-danger" })